name: Build macOS

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Install dependencies (Node)
        run: npm install

      - name: Get version
        shell: bash
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          args: --target aarch64-apple-darwin

      - name: Create PKG and Prepare Artifacts (macOS)
        shell: bash
        run: |
          ver="${{ env.VERSION }}"
          os="MacOS"

          app_path="src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Pulsar.app"
          pkg_name="Pulsar-$ver-$os.pkg"
          res_dir="pkg-resources"

          rm -rf "$res_dir"
          mkdir -p "$res_dir"
          cp public/assets/icons/icon.icns "$res_dir/Icon.icns"
          textutil -convert rtf LICENSE -output "$res_dir/License.rtf"

          productbuild --component "$app_path" /Applications --resources "$res_dir" "$pkg_name"
          cp src-tauri/target/aarch64-apple-darwin/release/bundle/macos/*.app.tar.gz "Pulsar-$ver-$os.app.tar.gz"
          cp src-tauri/target/aarch64-apple-darwin/release/bundle/macos/*.app.tar.gz.sig "Pulsar-MacOS.sig"

          echo "ASSET_INSTALLER=$pkg_name" >> $GITHUB_ENV
          echo "ASSET_UPDATER=Pulsar-$ver-$os.app.tar.gz" >> $GITHUB_ENV
          echo "ASSET_SIG=Pulsar-MacOS.sig" >> $GITHUB_ENV

      - name: Upload build artifacts (server)
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ github.ref_name }}
          path: |
            ${{ env.ASSET_INSTALLER }}
            ${{ env.ASSET_UPDATER }}

      - name: Upload Signature artifact
        uses: actions/upload-artifact@v4
        with:
          name: sig-macos
          path: ${{ env.ASSET_SIG }}

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ASSET_INSTALLER }}
            ${{ env.ASSET_UPDATER }}