name: Build macOS

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Install dependencies (Node)
        run: npm install

      - name: Get version
        shell: bash
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          args: --target aarch64-apple-darwin

      - name: Rename Artifacts and Extract Signature (macOS)
        shell: bash
        run: |
          ver="${{ env.VERSION }}"
          os="MacOS"

          cp src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg "Pulsar-$ver-$os.dmg"
          if ls src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.sig 1> /dev/null 2>&1; then
          cp src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg.sig "Pulsar-MacOS.sig"
          echo "ASSET_SIG=Pulsar-MacOS.sig" >> $GITHUB_ENV
          else
          echo "No signature found, skipping..."
          echo "ASSET_SIG=" >> $GITHUB_ENV
          fi

          cd src-tauri/target/aarch64-apple-darwin/release/bundle/macos
          ditto -c -k --sequesterRsrc --keepParent "Pulsar.app" ../../../../../../Pulsar-$ver-$os.zip
          cd -

          echo "ASSET_INSTALLER=Pulsar-$ver-$os.dmg" >> $GITHUB_ENV
          echo "ASSET_PORTABLE=Pulsar-$ver-$os.zip" >> $GITHUB_ENV
          echo "ASSET_SIG=Pulsar-MacOS.sig" >> $GITHUB_ENV

      - name: Upload build artifacts (server)
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ github.ref_name }}
          path: |
            ${{ env.ASSET_INSTALLER }}
            ${{ env.ASSET_PORTABLE }}

      - name: Upload Signature artifact
        uses: actions/upload-artifact@v4
        with:
          name: sig-macos
          path: ${{ env.ASSET_SIG }}

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ASSET_INSTALLER }}
            ${{ env.ASSET_PORTABLE }}
            ${{ env.ASSET_SIG }}