name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check changelog file
        run: |
          if [ ! -f .github/changelog.md ]; then
            echo "No changelog detected" > .github/changelog.md
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Pulsar ${{ github.ref_name }}
          body_path: .github/changelog.md
          draft: true
          prerelease: false